"""empty message

Revision ID: 23a0ef79535
Revises: 5476dd42f4c
Create Date: 2015-10-31 01:35:28.366840

"""

# revision identifiers, used by Alembic.
revision = '23a0ef79535'
down_revision = '5476dd42f4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('feelings_on_qr_codes', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'feelings_on_qr_codes')
    ### end Alembic commands ###
