"""empty message

Revision ID: 3eb7c2b7053
Revises: 23a0ef79535
Create Date: 2015-11-11 01:47:14.982509

"""

# revision identifiers, used by Alembic.
revision = '3eb7c2b7053'
down_revision = '23a0ef79535'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('whitelist', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'whitelist')
    ### end Alembic commands ###
