"""empty message

Revision ID: 40f80e32062
Revises: None
Create Date: 2015-11-21 18:23:25.869288

"""

# revision identifiers, used by Alembic.
revision = '40f80e32062'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('call_forwarding_set', sa.Boolean(), nullable=True),
    sa.Column('feelings_on_qr_codes', sa.Enum('love', 'hate', name='qr_code_enum'), nullable=True),
    sa.Column('whitelist', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailbox')
    ### end Alembic commands ###
