"""call_forwarding

Revision ID: 5256f3c602b
Revises: 144a1d39c99
Create Date: 2015-10-10 22:29:46.675846

"""

# revision identifiers, used by Alembic.
revision = '5256f3c602b'
down_revision = '144a1d39c99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('call_forwarding_set', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'call_forwarding_set')
    ### end Alembic commands ###
