"""empty message

Revision ID: 5476dd42f4c
Revises: 2946a4a70b4
Create Date: 2015-10-29 00:37:56.905983

"""

# revision identifiers, used by Alembic.
revision = '5476dd42f4c'
down_revision = '2946a4a70b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('email', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'email')
    ### end Alembic commands ###
